### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for xxx,  If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

### ISSUE THREAD

**Issue by chrisng2008** [zwhe99/X-SIR#1]
![image](https://github.com/zwhe99/X-SIR/assets/72513336/39dda473-1c73-4bdb-b05b-5bb5dadb9c24)

OSError: Unable to load weights from pytorch checkpoint file for '/home/chris/.cache/huggingface/hub/models--baichuan-inc--Baichuan-7B/snapshots/5d86e56a58fe4a5b3292cd9bb7468afef6f93eab/pytorch_model.bin' at '/home/chris/.cache/huggingface/hub/models--baichuan-inc--Baichuan-7B/snapshots/5d86e56a58fe4a5b3292cd9bb7468afef6f93eab/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by zwhe99** [comment]
Have you tried aligning the library version to mine and deleting the model cache?

**Comment by zwhe99** [comment]
We're going to close this issue as it appears to be inactive. @chrisng2008 , feel free to reopen it if you still have this problem.
