### ISSUE TITLE
code to reproduce CWRA attack

### ISSUE THREAD

**Issue by Allencheng97** [zwhe99/X-SIR#2]
Dear authors,

  Thank you for your great work. I checked the code but only find two baseline attack methods:paraphrase and translation in current repo. Is there any part in the release code contains full code to execute CWRA attack in  the paper?

  Thank you for your attention. I am looking forward to hearing from you soon.

Best

**Comment by zwhe99** [comment]
Sorry for the delay. You can use the "translation" attack multiple times to execute CWRA. For instance, translate the English prompt into Chinese, prompt the LLM in Chinese, and translate the Chinese response back into English.
